### ISSUE TITLE
้hey guy i error codeing spotsDialog java.lang.NullPointerException: 

### ISSUE THREAD

**Issue by PongPloy2016** [d-max/spots-dialog#20]
I catch error  progressbar 

  if (spotsDialog != null) {

                    spotsDialog.dismiss();
                    spotsDialog = null;
                } else {
                    spotsDialog.dismiss();
                    spotsDialog = null;
                }

and show logcaat 

 Process: th.co.siamkubota.kubota, PID: 24287
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void dmax.dialog.SpotsDialog.dismiss()' on a null object reference
                                                                             at th.co.siamkubota.kubota.fragment.UnfinishTaskFragment$1.onPostExecute(UnfinishTaskFragment.java:308)
                                                                             at th.co.siamkubota.kubota.fragment.UnfinishTaskFragment$1.onPostExecute(UnfinishTaskFragment.java:221)
                                                                             at android.os.AsyncTask.finish(AsyncTask.java:636)
                                                                             at android.os.AsyncTask.access$500(AsyncTask.java:177)
                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:145)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6856)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by d-max** [comment]
Hi! You have a wrong logic. I believe 'else' block is unnecessary :)

**Comment by matloobn73** [comment]
If (spotsDialog != Null){
//If spotsDialog is not null.
spotsDialog.dismiss;
spotsDialog = null;
}else{
//If spotsDialog is null.
//You can't do anything with spotsDialog as it is null.
//You don't have to call spotsDialog.dismiss as it is already null and hence dismissed.
}

**Comment by PongPloy2016** [comment]
> If (spotsDialog != Null){
> //If spotsDialog is not null.
> spotsDialog.dismiss;
> spotsDialog = null;
> }else{
> //If spotsDialog is null.
> //You can't do anything with spotsDialog as it is null.
> //You don't have to call spotsDialog.dismiss as it is already null and hence dismissed. 
> }

thank  you  bro  i check null  
If (spotsDialog != Null){
.....
}

 and  run project  and show catch error   In perhaps     : Attempt to invoke virtual method 'void dmax.dialog.SpotsDialog.dismiss()' on a null object reference  to some time
